### ISSUE TITLE
[bug] Doesn't like my US formatted phone number

### ISSUE THREAD

**Issue by samos123** [ppresume/community#22]
## Description

Some valid US phone numbers get "invalid" error warning

## To Reproduce

1. Create or update a resume
2. Type `+1 (650) 432-6289` for phone number in basics section

### Actual Behavior

PPResume reports `Phone number is invalid` warning

### Expected Behavior

This is a valid US phone and should not get invalid phone number warning

## [Optional] Screenshots

Screenshot:
<img width="395" alt="image" src="https://github.com/ppresume/community/assets/388784/6040a456-07bc-41ca-83da-4f517bd94239">

### Desktop

NA

### Smartphone

NA

## Additional Context

NA

**Comment by xiaohanyu** [comment]
Fixed and deployed, preview:

Uploading ppresume-phone-number-validation.mp4…
