### ISSUE TITLE
feat: auth: social sign in with Google

### ISSUE THREAD

**Issue by xiaohanyu** [ppresume/community#7]
## Description

As title, we want to support social sign in with Google

## [Optional] Possible solutions

NA

## Acceptance Criteria

- user should be able to sign in with his/here google account
- if the email already signed up, then the user signed in with google should be treated the same as the user signed in plain username/email

## Todo list

```[tasklist]
- [x] check google documentation to see how to support social sign in with google account
- [x] implement the logic for social sign in with google account
```

**Comment by xiaohanyu** [comment]
After some evaluation we found that this is a bit hard to implement right.

Strapi (yes we use strapi in our backend) does not support one user to use multiple auth providers right now, check the [issue](https://github.com/strapi/strapi/issues/2468) and [form](https://feedback.strapi.io/security/p/multiple-authentication-providers-per-user).

There're some essential trickies to get it right here.

Let's say that we have a user registered via plain credentials, with username `foo` and email `foo@example.com`, then another user want to sign in via Google OAuth, with gmail account `foo@gmail.com`, then it is highly likely that the system would lead to duplicated username of `foo`, which would break lots of things.

Other CMS like [directus] seems have similar [issue](https://github.com/directus/directus/discussions/9088?sort=top).

Let's postpone this issue and see whether strapi official could come up with better solution.

**Comment by xiaohanyu** [comment]
This is finally implemented and put online with the help of logto:

<img width="1608" alt="google-sign-in" src="https://github.com/ppresume/community/assets/1164623/9accbd1b-48fd-4990-b8f1-4038904c1ad7">
<img width="1608" alt="google-sign-in-account-linking" src="https://github.com/ppresume/community/assets/1164623/295f5826-fc15-4c1d-8f4b-a42d7e3cad69">
<img width="1608" alt="google-sign-in-oauth-consent-screen" src="https://github.com/ppresume/community/assets/1164623/aa1e28c3-ad78-4f2c-aba0-f4589628ea40">

**Comment by Davidosky007** [comment]
@xiaohanyu please how can this solution be implemented, i currently face this issue
